name = "MeshExtrusions"
uuid = "03d05e0c-52e7-4868-8973-a4323c22e768"
authors = ["Cris Moen <cris.moen@runtosolve.com>"]
version = "0.1.0"

[deps]
CrossSectionGeometry = "e5713cf4-1a83-4860-95bf-b82253e75fb4"
